name: aoc download
description: Download puzzle input from Advent of Code (https://adventofcode.com/)
author: Tobias Bell
inputs:
  year:
    description: For which year to download (default current year)
    required: false
  day:
    description: For which day to download (default current day)
    required: false
  output:
    description: |
      Path where the puzzle input will be stored. Can be templated with the variables
      $day and $year. For year 2015, day 01 and output_path "$year/day$day" you get 2015/day01
    required: false
    default: day$day
  session:
    description: Session key from the Advent of Code page
    required: true
runs:
  using: composite
  steps:
    - id: validate
      run: |
        if [[ -z "$session" ]]; then
          echo "::error ::session cookie must be set"
          exit 1
        fi
        echo "::add-mask:$session"

        current_year=$(date +%Y)
        current_month=$(date +%m)
        if [[ -z "$year" ]]; then
          year=$(date +%Y)
        fi

        if [[ -z "$day" ]]; then
          day=$(date +%d)
        fi

        if [[ "$year" -eq "$current_year" && "$current_month" -ne 12 ]]; then
          echo "::error ::downloads in the future ($year-$month-$day) are not possible"
          exit 1
        fi

        output=${output//\$year/$year}
        output=${output//\$day/$day}

        echo "year=$year" >> "$GITHUB_OUTPUT"
        echo "day=$day" >> "$GITHUB_OUTPUT"
        echo "output=$output" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        TZ: EST
        session: ${{ inputs.session }}
        year: ${{ inputs.year }}
        day: ${{ inputs.day }}
        output: ${{ inputs.output }}
    - id: download
      run: |
        curl --proto '=https' --tlsv1.2 \
          --retry 3 --retry-connrefused \
          --cookie "session=$session" \
          --user-agent "github.com/tobidope/aoc-download" \
          --fail --silent --show-error \
          --location --output "$output" "$url"
      shell: bash
      env:
        output: "${{ steps.validate.outputs.output }}"
        session: ${{ inputs.session }}
        url: >
          https://adventofcode.com/${{ steps.validate.outputs.year }}/day/${{ steps.validate.outputs.day }}
